### ISSUE TITLE
Tag Questions

### ISSUE THREAD

**Issue by timjogorman** [amrisi/amr-guidelines#163]
While retrofitting "right", we ended up running into a bunch of [tag questions](https://en.wikipedia.org/wiki/Tag_question), and we seem to generally have done them quite inconsistently.

"tag question" is one of the terms for constructions where someone adds a reduced question to the end of a (usually declarative) clause, which generally adds some sort of "request for confirmation" meaning, as with ", right?", "didn't you?", "isn't it?", and in some dialects, "yeah?" or "eh?"

##### :mode interrogative (most common treatment)
*" It is true , is n't it , that sheep eat little bushes ? "*
true :mode interrogative

*"Well, just telling you who I'll vote for probably won't inform you much though right?"*
p2 / probable :mode interrogative

#####  :mode interrogative + :ARG2-of (r3 / right-06))  or :mode interrogative + :mod (r2 / right) 
*Since the laws already exist in the US and have since 1968, your fear of losing your weapon has obviously been realized, right?.*

(r3 / realize-02 :mode interrogative 
  ... :ARG2-of (r4 / right-06) 

*in the US we have thought communist regimes were thugs and goons since Stalin in the 50s right?*
(t / think-01 :mode interrogative 
.. :mod (r2 / right) 

#### :ARG2-of (r3 / right-06 :mode interrogative)
*You guys realize that when you have rabid anti-Obama RWers with Obama-Derangement Syndrome like Ghooks making public statements like this means that the GOP is toast this election right?*
   :ARG2-of (r3 / right-06 :mode interrogative)) 

##### Option 1: Just consistently map these to :mode interrogative

I'm not happy with this semantically, but the most common analysis is that this is :mode interrogative.  This means that we are giving the same reading to:

"is it a hot day?"
"hot day, isn't it."
or 
* *did you submit the paper?*
* *you submitted the paper, right?*

##### Option 2: add a mode or frame for it, like :mode tag-question or :mode request-confirmation

Tag questions seem to be a  pretty typologically common thing appearing in a number of languages  -- although some have different syntactic ways of doing them (e.g. Persian and  Gaelic repeat the verb itself as a question).  So it seems sane to just have it as a separate concept. 

I'd prefer to add something like ":mode tag-question", to simply encode this middle ground between interrogative mode and assertion, as I don't think that any of the example sentences above are actually synonymous with their :mode interrogative equivalents. That said, we all define 1/8 of an inch differently, right?

**Comment by nschneid** [comment]
This is a really interesting issue that makes me realize how little I know about discourse and pragmatics.

One precedent is that emphasis is dropped in AMR: e.g., the AMR Dictionary gives the example "Yes, I know" = "I know". "Yes" in this sentence indicates a confirmation. Tag questions *request* a confirmation. Would it be inconsistent to ignore the confirmation-signal but include the confirmation-request?

I tentatively think I am in favor `:mode tentative` for not-quite-assertions, because they *are* different from straight questions: they indicate a proposition that is expected to be correct. Which makes me wonder if the same should apply to hedges ("He sort of fell into the job").

But one complication is that tag questions are sometimes deployed for rhetorical or stylistic reasons; the speaker is not actually unsure of the truth value of the proposition. For example, to drive home one's point in an argument or confrontation, as if forcing the opponent to reconsider their logic: 

> You’re in trouble, you are! Didn’t the headmaster say that nighttime prowling’s out, unless you’ve got permission, didn’t he, eh? — Filch in _Harry Potter and the Half-Blood Prince_

I don't think Filch is being tentative at all. So it seems like we need to decide what slice, if any, of this construction's semantics/pragmatics/rhetorical effect belongs in the AMR.

**Comment by ulfulf** [comment]
I agree that tag questions are not just simple interrogatives.

Interestingly, in Spanish, only the tag question tags are included in the pair of question marks:
```
Estás cansado, ¿verdad? (You're tired, aren't you?)
```
which further supports the view that tag questions differ from simple interrogatives.

Imperatives can have question tags as well: *Come here, will you?*
```
(c / come-01 :mode imperative :mode "tag-question/request-confirmation"
      :ARG1 (y / you)
      :ARG4 (h / here))
```

**Comment by ulfulf** [comment]
Decision at AMR phone meeting on Dec. 7, 2015:
* Add new frame request-confirmation-91
* Expand AMR Dict: http://www.isi.edu/~ulf/amr/lib/amr-dict.html#tag%20question
