### ISSUE TITLE
Smatch and time entities

### ISSUE THREAD

**Issue by mdtux89** [amrisi/amr-guidelines#172]
On this example taken from the guidelines:

```
(d / date-entity
   :month 2
   :day 29
   :weekday (w / wednesday)
   :time 16:30
   :timezone (z / PST))
```

 smatch gives the error:

```
Error in processing; part len < 2 (d / date-entity:month 2:day 29:weekday (w / wednesday):time 16:30:
Traceback (most recent call last):
  File "smatch.py", line 835, in <module>
    main(args)
  File "smatch.py", line 735, in main
    amr1.rename_node(prefix1)
```

I think the problem is that Smatch interprets ":30" as a role. One easy way around the problem is to put 16:30 in quotes.
Marco

**Comment by nschneid** [comment]
You're right, [it should be in quotes](http://www.isi.edu/~ulf/amr/lib/popup/date.html). This has been fixed in the latest AMR for the sentence. You can see it by doing a release search (`rs`) in the AMR Editor (i.e., searching for all AMRs intended for release). The command `rs wednesday 2 29` will bring up:

[1]   consensus   isi_0002.7   (snt. 45 in workset  guidelines, last updated on Mon May 14, 2012)
Wednesday, February 29, 2012, at 4:30pm PST

(d / date-entity :month 2 :day 29 :year 2012 :time "16:30" :timezone "PST" 
      :weekday (w / wednesday)) 

(You can see that the timezone is now also a string.)

**Comment by mdtux89** [comment]
Thanks. I think also the guidelines in amr.md should be updated accordingly.
