### ISSUE TITLE
Possible-01 in degree/quant-consequence constructions

### ISSUE THREAD

**Issue by cbonial** [amrisi/amr-guidelines#221]
You can now find Ulf's latest dictionary entry for have-degree-91 and have-quant-91 and updated guidelines instances (https://www.isi.edu/~ulf/amr/lib/amr-dict.html#:degree).  So retrofitting can begin barring this -- the only issue nagging at me is when to use "possible" with degree-consequence constructions.  To me, things like "It's too early to reach any conclusion" and "He is not tall enough to ride the rollercoaster" seem to invoke something like "It's too early/he's not tall enough, therefore we/he COULDN'T conclude/ride the rollercoaster" -- where the negation should properly be on the possibility rather than the conclude/ride event.  This seems to apply generally to all of the negated versions of these constructions, and parallel quant constructions -- "I had too many books to carry," i.e. "I had too many books, therefore I couldn't carry them."  But what does that mean for the non-negated versions?  Should "The computer is small enough to fit in your pocket" have a possible-01 node, indicating that it COULD fit in your pocket, but not necessarily that anyone did fit it in your pocket? This seems a little over the top, and especially strange in past tense cases where it seems clear that the consequence did happen: "I had scarcely enough drinking water to last a week," i.e. I had enough drinking water, therefore it lasted a week.

I think options are: 
1. presume that the "possibility" is somehow encoded in the consequence role itself, remove from all cases
2. add "possible" to all negated cases, where the consequence could not or did not occur
3. add "possible" to consequence arg of all cases of degree-consequence -- whether positive or negative
4. perhaps this choice can be made on a case-by-case basis using context? 

Thanks for your input.

**Comment by ulfulf** [comment]
I think that any addition of (possible-01 :polarity -) etc. needs to be considered on a case by case basis. IMO "fit-06" does not need possible-01, since fit-06 already implies that something possibility, not the fact, that something can be placed inside something else. (Some shirts fit even if they have never been worn.)

*He is not tall enough to ride the rollercoaster.*
```
(h / have-degree-91
      :ARG1 (h2 / he)
      :ARG2 (t / tall)
      :ARG3 (e / enough :polarity -)
      :ARG6 (p / permit-01 :polarity -
            :ARG1 (r / ride-01
                  :ARG0 h2
                  :ARG1 (r2 / rollercoaster))))
```
In the example above, I would add a negation to "enough" and maybe prefer permit-01 over possible-01. He is NOT tall enough, therefore he is not PERMITTED to ride the rollercoaster (for safety reasons).

**Comment by nschneid** [comment]
My gut instinct is that option 1 (presume modality is captured in the consequence role; the construction does not specify that the consequence is realis) is the safest. 

In the roller coaster example, it seems like the permission vs. possibility distinction is one of inference, not sentence meaning: all the sentence says is that his being short prevents him from riding, not *why* he is prevented from riding.

And I suspect it's not just possibility and permission modalities that come into play: "The water level is too low for it to have rained." would be epistemic, right? "He is too young to play piano" could mean his youth makes him unable to play because he lacks the ability, or that his parents prevented him, or that there is a cultural norm about piano-playing ages....

**Comment by cbonial** [comment]
Thanks, Ulf and Nathan for your thoughts.  

Ulf -- I feel strongly that the common core of this construction -- whether the consequence is negated or not -- is that there is a scalar property, and the degree to which this scalar property holds determines whether or not the consequence holds.  I think adding the "not" to enough is somewhat superficial/syntactic in nature and wouldn't capture this common core between "He's not tall enough to ride the rollercoaster" and "He's too short to ride the rollercoaster" -- In both cases there is a degree to which the scalable property of height holds, and as a result he cannot ride the rollercoaster.  I don't really know what negating a degree would "mean" on a deep level, in comparing these two constructions that I think should have very similar AMRs.  

Nathan -- I'm starting to lean towards this option as well, we could add a note explicitly stating that construction doesn't specify whether consequence is realis/irrealis. I agree that teasing apart which contexts call for inclusion of modality and what type requires too much extra-linguistic knowledge, and capturing only what we do know with certainty from the construction is safest: although we do not know whether the consequence is realis/irrealis, we do know its polarity (no piano playing was possible vs. it's light enough to pick it up and throw it! -- throwing it IS possible (although we don't know if you did/should throw it)).

**Comment by ulfulf** [comment]
Hmm, I'm a bit confused. Surely we want to annotate "He is tall enough." and "He is not tall enough." differently.
Maybe we want to recast :ARG6 as a reference in respect to which something is sufficiently or insufficiently the case, in which case :ARG6 will no longer be burdened with transferred negations and impossibilities.

Claire's original annotation:

He is not tall enough to ride the rollercoaster.
```
(h / have-degree-91
      :ARG1 (h2 / he)
      :ARG2 (t / tall)
      :ARG3 (e / enough)
      :ARG6 (r / ride-01
            :ARG0 h2
            :ARG1 (r2 / rollercoaster)
            :ARG1-of (p / possible-01 :polarity -)))
```

Alternative:
```
(h / have-degree-91 :polarity -
      :ARG1 (h2 / he)
      :ARG2 (t / tall)
      :ARG3 (e / enough)
      :ARG6 (r / ride-01
            :ARG0 h2
            :ARG1 (r2 / rollercoaster)))
```

It is too early to reach any conclusions.
```
(h / have-degree-91 
      :ARG2 (e / early) 
      :ARG3 (t / too) 
      :ARG6 (c / conclude-01))
```
This annotation does not make explicit the inference that conclusions are currently impossible, but AMR generally does not encode inferences (such as "John is taller than Mike and Mike is taller than Bill." => "John is taller than Bill.")

**Comment by nschneid** [comment]
@ulfulf's alternative looks good to me.

I guess we can think of the regions of a scale as follows: 

- With respect to a lower bound: insufficiently X = not X enough, vs. sufficiently X = X enough
- With respect to an upper bound: not excessively X = not too X, vs. excessively X = too X
- The consequence is realized if sufficiency but not excess is met. This feels like something that is inferred compositionally using the meaning of "too" or "enough", not stated directly.

**Comment by nschneid** [comment]
Now I'm trying to figure out how "so X that Y" works. It is similar to "enough", but I think Y either has to have an explicit modal in it, or be realis. Compare:

- The winds were 100mph, strong enough to knock big trees over. [implied possibility]
- The winds were 100mph, so strong that they could have knocked big trees over. [possibility due to "could have"]
- The winds were 100mph, so strong that they knocked big trees over. [actuality]
- ?The winds were 100mph, so strong as to knock big trees over. [possibility?]

With negation:

- The winds weren't strong enough to knock big trees over. [impossibility]
- The winds weren't so strong that they could have knocked big trees over. [impossibility due to "not" + "could have"]
- ??The winds weren't so strong that they knocked big trees over.
- The winds weren't so strong as to knock big trees over. [impossibility due to "not" + "as to"?]
Using "so" also suggests a high degree, whereas "enough" just suggests the degree is above a minimum threshold.

Suggestion: to the AMR Dictionary, add a discussion of degree-consequence *so*, and (based on a COCA corpus search) also note that "not so sure that Y" is ambiguous. It often means "not very sure", e.g. "I'm not so sure that I remembered to turn off the stove."

**Comment by ulfulf** [comment]
Consensus on AMR phone meeting on Sept. 18, 2017
Interpret :ARG6 as reference rather than consequence.
Don't annotate :ARG6 with any transferred negations or impossibilities, which might vary from case to case and might confuse annotators.
Largely go with Ulf's alternatives above and add example with "so" per Nathan's suggestion above.

From updated guidelines:
Annotators should introduce the most logical relation fitting with the context. Although it may be tempting to introduce modality, possibility, and/or polarity in the consequence (i.e. expressing that there is NO conclusion), a survey of these constructions has demonstrated the difficulty in introducing such elements consistently in context. Therefore, annotators are asked to limit the Arg6 to the simple relation to which the degree has reference. See AMR Dictionary for additional examples. Negative polarity should only be introduced (modifying have-degree-91) when it is explicit.
